[theme]
base="light"
primaryColor="#00C9A7"                # Vert-turquoise lumineux
backgroundColor="#F9FAFB"             # Presque blanc
secondaryBackgroundColor="#FFFFFF"    # Cartes et encadrés
textColor="#111827"                   # Noir doux
font="sans serif"
